version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/install-deps
      - run:
          command: python setup.py test
          name: Unit tests
      - run:
          command: flake8 asr_evaluation
          name: Style check

workflows:
  main:
    jobs:
      - build-and-test
